schema_version: 1

context:
  name: lightrag-hku
  version: 1.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lightrag_hku-${{ version }}.tar.gz
  sha256: d5a444eb6f213911ebb1dc641a4fa34b52b008315a4582c4110c0d03a461fd4b
  patches:
    - requirements.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - tiktoken
    - networkx
    - nano-vectordb
    - tenacity
    - pydantic
    - packaging
    - pipmaster
    - numpy >=1.24.0,<3.0.0
    - xlsxwriter >=3.1.0
    - configparser
    - google-api-core >=2.0.0,<3.0.0
    - pyyaml >=6.0,<7.0
    - pandas >=2.0.0,<2.4.0
    - pypinyin
    - aiohttp
    - python-dotenv
    - google-genai >=1.0.0,<3.0.0
    - setuptools
    - json-repair
tests:
  - python:
      imports:
        - lightrag
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: 'LightRAG: Simple and Fast Retrieval-Augmented Generation'
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/HKUDS/LightRAG

extra:
  recipe-maintainers:
    - jan-janssen
