schema_version: 1

context:
  name: lightrag-hku
  version: 1.4.15

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lightrag_hku-${{ version }}.tar.gz
  sha256: 50a2c26612c96dec1816150d39c121b8f090ff6bb00b485bc867e008923a858c
  patches:
    - requirements.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - tiktoken
    - networkx
    - nano-vectordb
    - tenacity
    - setuptools
    - google-api-core >=2.0.0,<3.0.0
    - google-genai >=1.0.0,<2.0.0
    - packaging
    - json-repair
    - pipmaster
    - python-dotenv
    - pypinyin
    - pydantic
    - configparser
    - xlsxwriter >=3.1.0
    - aiohttp
    - pandas >=2.0.0,<2.4.0
    - numpy >=1.24.0,<3.0.0
tests:
  - python:
      imports:
        - lightrag
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: 'LightRAG: Simple and Fast Retrieval-Augmented Generation'
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/HKUDS/LightRAG

extra:
  recipe-maintainers:
    - jan-janssen
